### ISSUE TITLE
Manifesto Text is overflowing the screen width

### ISSUE THREAD

**Issue by ORKO06** [codeisscience/journal-policy-tracker-frontend#66]
Thank you for taking the time to file a Bug report.

**Describe the bug**
If you visit the manifesto and then inspect it then on a screen less than 900 px widths the Manifesto heading text is not made responsive as its font size is fixed to 5em

**To Reproduce**

1. Go to '[https://journal-policy-tracker.netlify.app/manifesto](https://journal-policy-tracker.netlify.app/manifesto)'
2. Right-click the mouse button and then click on 'inspect '
3. Keep the dimension responsive and make the screen size less than 900 px.
4. See the Manifesto title text getting overlay by image first and then for screen size smaller than 450px it is making the page unresponsive

**Expected behavior**
The Manifesto title text should have a responsive font size which should not overflow the screen width.

**Screenshots**
![image](https://user-images.githubusercontent.com/74568847/160880296-c887062c-d413-4071-947c-1b19759d3d2a.png)

**Desktop (please complete the following information):**

- OS: [Windows]
- Browser [Brave]

**Comment by aminoxix** [comment]
@ORKO06: Shall I work on this issue?

**Comment by ORKO06** [comment]
@amino19 I am currently working on it.

**Comment by amino19** [comment]
> @amino19 I am currently working on it.

There's nowhere mentioned, that you're working on this issue.

**Note:**
- If you're contributing to any other organizations' project, you must be very specific about your deeds, because it's a team effort, & I hope you don't want conflicts via miscommunication.
- If you're raising any issue, write it down as a `Note` or recomment over there, that you're working on that issue. :slightly_smiling_face: 

Happy Contributing! : )

**Comment by aminoxix** [comment]
> @amino19 I am currently working on it.

There's nowhere mentioned, that you're working on this issue. Since there are no assignees yet, I'm taking this issue from my end.

**Note:**
- If you're contributing to any other organizations' project, you must be very specific about your deeds, because it's a team effort, & I hope you don't want conflicts via miscommunication.
- If you're raising any issue, write it down as a `Note` or recomment over there, that you're working on that issue. :slightly_smiling_face: 

Happy Contributing! : )

@padmajabhol: It would be great to hear from you and your insights on it?

**Comment by ORKO06** [comment]
@amino19 I didn't know about it. I hope you can take any other issue. I apologize from my behalf for the miscommunication.

**Comment by padmajabhol** [comment]
Hi @amino19, most os organisations have different code of conduct and what you see here can differ elsewhere and it's pretty diverse out there. 
And I believe if a contributor takes the pain to navigate through a project to find bugs, they should ideally be assigned to it( if they want). 
I'm not a maintainer here and the current maintainers can be pretty busy so I request you to have patience. Happy contributing 🐻

**Comment by padmajabhol** [comment]
@ORKO06 are you working on this? If not, could you like to pass it to someone else?

**Comment by ORKO06** [comment]
@padmajabhol I am currently working on this. My work is almost ready and will sent a pr pretty soon.

**Comment by vedeepika** [comment]
Shall I work on this issue?

**Comment by dikshashukla455** [comment]
Can I work on this issue? If no one is assigned

**Comment by yochannah** [comment]
Hey @dikshashukla455 and @vedeepika thanks both for volunteering - we usually prefer to give the first person who comments on as issue the chance to finish it first though. You're welcome to work on other issues or make issues if you spot one!

**Comment by aminoxix** [comment]
> Hey @dikshashukla455 and @vedeepika thanks both for volunteering - we usually prefer to give the first person who comments on as issue the chance to finish it first though. You're welcome to work on other issues or make issues if you spot one!

But, it's approximately a week, and the contributor is busy making as much as a contribution for GSoC; so at least another contributor must have a chance. :slightly_smiling_face:

**Comment by oneknucklehead** [comment]
Is this issues still being worked upon? If not, can I be assigned to this issue?
