### ISSUE TITLE
Mock up UI for front end - journal submission

### ISSUE THREAD

**Issue by yochannah** [codeisscience/journal-policy-tracker-frontend#8]
Goal: set up a UI to allow people to submit data - currently we have this form: https://docs.google.com/forms/d/e/1FAIpQLScckKkSwH1nW22G8u0_GMRKk1KAV7SQGxaRsH6ysLecS9EHFQ/viewform

feel free to use wireframing software or a pen and paper sketch to get this done.

**Comment by yochannah** [comment]
@ikayz might look at this if/when free

**Comment by td-heisenbug** [comment]
[CIS.zip](https://github.com/codeisscience/codecompliance-frontend/files/6261972/CIS.zip)

**Comment by yochannah** [comment]
@td-heisenbug wow, this is really pretty! Did you use a CSS framework at all?

I know @ikayz has some mockups he's been working on too.

**Comment by td-heisenbug** [comment]
> @td-heisenbug wow, this is really pretty! Did you use a CSS framework at all?
> 
> I know @ikayz has some mockups he's been working on too.

Thank You.
Yea I modified one a bit to suit better.

**Comment by JPTIZ** [comment]
That looks very interesting indeed :) My only issue is that the submit button gets too flashy when you hover it (see the video below). I would prefer something more subtle, just something slightly brighter than the unhovered button color.

https://user-images.githubusercontent.com/11988816/114245813-924af800-9967-11eb-8f36-4604bf000be8.mp4

Besides that, would be good indeed to align with @ikayz's mockups. Isaac, would you mind sharing them here?

---

On a side-note, @td-heisenbug, two small tips:
- When sharing compressed files (zip, tgz), please prefer compress a directory instead of the files directly. This prevents a straight forward "extract here" from messing the current directory with apparently contextless files.
- Whenever possible, sharing a visual preview of your work - when applicable - would be very helpful when reviewing :)

**Comment by td-heisenbug** [comment]
@JPTIZ 

Thank You. Yes I could make the button a bit more subtle. I will keep in mind.

>  When sharing compressed files (zip, tgz), please prefer compress a directory instead of the files directly. This prevents a   straight forward "extract here" from messing the current directory with apparently contextless files.
   
> Whenever possible, sharing a visual preview of your work - when applicable - would be very helpful when reviewing :)

Sorry for the inconvenience. I will make sure to follow these while contributing next time.
